apiVersion: v1
kind: Service
metadata:
  name: crypto-ticker-service
  labels:
    app: crypto-ticker
spec:
  selector:
    app: crypto-ticker
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
